### ISSUE TITLE
使用Mask Language Model加载模型预测的结果不对

### ISSUE THREAD

**Issue by AnShengqiang** [nghuyong/ERNIE-Pytorch#1]
您好，我尝试用pytorch-pretrained-BERT里面的BertForMaskedLM去加载您转换的模型，然后预测被mask的词语，发现预测到的结果并不正确，请问这是什么原因？是不是ERNIE和BERT的Mask Language Model两者网络结果不一样呢？😿

**Comment by nghuyong** [comment]
是，这个现在不支持BertForMaskedLM
