### ISSUE TITLE
咨询版本问题

### ISSUE THREAD

**Issue by renjunxiang** [nghuyong/ERNIE-Pytorch#13]
你好，我在几个月前fork过您的这个项目，当初只有一个ernie，地址是<http://image.nghuyong.top/ERNIE.zip>。现在您这里有两个，这两个区别在哪。当初您开源的是哪一个呢？万分感谢！

**Comment by nghuyong** [comment]
之前的发布的，ERNIE 1.0 模型，预训练数据长度为 128
现在的两个一个预训练阶段的数据长度是128，一个预训练阶段数据长度是512
谢谢提醒，已经更新的reamde。
