### ISSUE TITLE
about ernie2.0

### ISSUE THREAD

**Issue by geniusSDNexplorer** [nghuyong/ERNIE-Pytorch#14]
hello,sir
when will you support the version 2.0?
thankyou

**Comment by nghuyong** [comment]
OK, if time is enough, I will support.
Thank you~

**Comment by AMR-KELEG** [comment]
Hi @nghuyong,
Could you please tell me what was the idea for converting a paddle implementation to a pytorch one?
I would be really grateful to help you in supporting ERNIE V2.0
