### ISSUE TITLE
百度的模型少了一点儿参数

### ISSUE THREAD

**Issue by jcheunglin** [nghuyong/ERNIE-Pytorch#15]
Weights of BertForMaskedLM not initialized from pretrained model: ['cls.predictions.decoder.weight']
作者遇到这个问题没有呢

**Comment by nghuyong** [comment]
这个参数不是bert的参数，所以没有提取这个参数

**Comment by nghuyong** [comment]
你可以使用convert_ernie_to_pytorch_v2.py来提取，具体见readme
