### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by ZhaoxinRuc** [nghuyong/ERNIE-Pytorch#17]
TypeError: __array__(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.Tensor) -> array

Invoked with: <paddle.fluid.core_avx.LoDTensor object at 0x7ffa07d52ca8>, dtype('float32')

**Comment by nghuyong** [comment]
Please make sure your paddle version is right
