### ISSUE TITLE
转换ernie2.0-large-en模型后用huggingface's Transformer测试结果报错

### ISSUE THREAD

**Issue by Ryanro** [nghuyong/ERNIE-Pytorch#24]
size mismatch for bert.encoder.layer.20.output.dense.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 3072]).
	size mismatch for bert.encoder.layer.21.intermediate.dense.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1024]).
	size mismatch for bert.encoder.layer.21.intermediate.dense.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for bert.encoder.layer.21.output.dense.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 3072]).
	size mismatch for bert.encoder.layer.22.intermediate.dense.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1024]).
	size mismatch for bert.encoder.layer.22.intermediate.dense.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for bert.encoder.layer.22.output.dense.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 3072]).
	size mismatch for bert.encoder.layer.23.intermediate.dense.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1024]).
	size mismatch for bert.encoder.layer.23.intermediate.dense.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for bert.encoder.layer.23.output.dense.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([1024, 3072]).

**Comment by nghuyong** [comment]
已经修复啦～详见readme
