### ISSUE TITLE
关于ernie-1.0的max_position_embeddings

### ISSUE THREAD

**Issue by AliceNEET** [nghuyong/ERNIE-Pytorch#30]
在下载的文件config.json中，有参数max_position_embeddings=513，这是模型参数要求，还是错误呢？
![image](https://user-images.githubusercontent.com/20288016/96394889-c550d200-11f5-11eb-817a-a19084ccbe3e.png)

**Comment by nghuyong** [comment]
word_embedding的参数是固定的，这个不能修改
position_embedding的参数也是固定的，不能修改
这些参数是预训练模型使用的固定的参数
