### ISSUE TITLE
处理微博数据集的时候遇到的问题

### ISSUE THREAD

**Issue by Haitao2587** [nghuyong/ERNIE-Pytorch#32]
微博数据集中有一些emoji，但是我使用加载ernie-1.0的tokenizer去encode这些emoji，如：\ue305，却无法得到相应的结果。tokenizer直接忽略了这些词。请问这时候该如何处理呢。

**Comment by nghuyong** [comment]
对，这些emoji处理不了，会处理成为 <UNK>
因为ernie模型在预训练阶段也没有针对emoji进行预训练。
