### ISSUE TITLE
Ernie 1.0转换失败

### ISSUE THREAD

**Issue by bluestinger** [nghuyong/ERNIE-Pytorch#33]
我看了下代码知道能在paddle 2.0下work，paddle 1.6 版本转换失败，这个怎么转？

**Comment by bluestinger** [comment]
Ernie 1.0模型在paddle 2.0下的参数要比1.6少，转换字典对应不上。

**Comment by nghuyong** [comment]
我是基于paddle 1.8转换的，具体见`requirements.txt`
你也可以直接下载转换好的模型
