### ISSUE TITLE
> 请参考readme中的调用方法

### ISSUE THREAD

**Issue by 0x0004** [nghuyong/ERNIE-Pytorch#37]
> 请参考readme中的调用方法

不在huggingface里调用，只用到模型和vocab的话，怎么处理。。。

_Originally posted by @0x0004 in https://github.com/nghuyong/ERNIE-Pytorch/issues/36#issuecomment-839619348_

**Comment by 0x0004** [comment]
https://github.com/nghuyong/ERNIE-Pytorch/issues/36#issuecomment-839645932

**Comment by nghuyong** [comment]
如果在Pytorch中直接load转换以后的pytorch_model.bin文件即可，如果是tensorflow也是同样加载模型文件

**Comment by 0x0004** [comment]
> 如果在Pytorch中直接load转换以后的pytorch_model.bin文件即可，如果是tensorflow也是同样加载模型文件

请问使用本项目转换后得到的vocab.txt，是17964的，还是18000的，因为如果使用huggingface里的vocab.txt，会报错，```
RuntimeError: Error(s) in loading state_dict for Classifier:
        size mismatch for embedding.word_embedding.weight: copying a param with shape torch.Size([18000, 768]) from checkpoint, the shape in current model is torch.Size([17964, 768]).
```

**Comment by nghuyong** [comment]
https://huggingface.co/nghuyong/ernie-1.0/blob/main/config.json
18000

**Comment by 0x0004** [comment]
> https://huggingface.co/nghuyong/ernie-1.0/blob/main/config.json
> 18000

https://huggingface.co/nghuyong/ernie-1.0/blob/main/vocab.txt
行数是17964...

**Comment by nghuyong** [comment]
以18000为准

**Comment by 0x0004** [comment]
> 以18000为准

对，问题就出在这，怎么样才能得到1800的vocab.txt

**Comment by nghuyong** [comment]
@linjian93  我看你已经关闭了issue，你找到问题的原因了吗

**Comment by linjian93** [comment]
> @linjian93 我看你已经关闭了issue，你找到问题的原因了吗？
> 下载了百度的原始模型文件重新核实了一遍，https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
> 确实config文件中的词表是18000，而vocab.txt中的行数是17964，模型搭建还是以config中的为准

config 中词表和 vocab.txt 行数不一致的问题，我当时确实已经解决了，不过时间太久远了，已经忘了当时怎么解决的，等我有空再来填坑。
