### ISSUE TITLE
Inference result different

### ISSUE THREAD

**Issue by TengliEd** [nghuyong/ERNIE-Pytorch#39]
@nghuyong the pooled_output[0] from input with batch size equal 1, say torch.tensor([tokenizer.encode('Hello world', add_special_tokens=True)]), is different from the pooled_output[0] feature from torch.tensor([tokenizer.encode('Hello world', add_special_tokens=True), tokenizer.encode('Hello world', add_special_tokens=True)]). Can anyone explain it ?

**Comment by nghuyong** [comment]
please try the latest version
