### ISSUE TITLE
Incompatible function aruments

### ISSUE THREAD

**Issue by Tarpelite** [nghuyong/ERNIE-Pytorch#4]
Hello, I download the Baidu model and run the scripts following the instruction.
But some errors happened, could you help me solve it?
Thanks very much for your work.

```
===================extract weights start====================
model config:
attention_probs_dropout_prob: 0.1
hidden_act: relu
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
max_position_embeddings: 513
num_attention_heads: 12
num_hidden_layers: 12
type_vocab_size: 2
vocab_size: 18000
------------------------------------------------
Traceback (most recent call last):
  File "convert_ernie_to_pytorch.py", line 136, in <module>
    state_dict = extract_weights(args)
  File "convert_ernie_to_pytorch.py", line 94, in extract_weights
    fluid_array = np.array(fluid_tensor, dtype=np.float32)
TypeError: __array__(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.Tensor) -> array

Invoked with: <paddle.fluid.core_avx.LoDTensor object at 0x7fe2ee529c00>, dtype('float32')

```

**Comment by nghuyong** [comment]
Hello, I can't reproduce your problem. The following is my running log just now
![image](https://user-images.githubusercontent.com/16462374/61179472-a4cebb00-a635-11e9-82cc-8290637689d5.png)
So, I think, maybe, it is the problem of your environment. 
And you could download my released version first, and it is the same with converted by yourself.

**Comment by ZhaoxinRuc** [comment]
I have the same problem, could you tell me the reason if you solve it? Thank you very much!
