### ISSUE TITLE
大神，ernie-gram并不适用。有解决办法吗

### ISSUE THREAD

**Issue by languandong** [nghuyong/ERNIE-Pytorch#40]

**Comment by YuzaChongyi** [comment]
ernie-gram 似乎是没有mlm层权重？

**Comment by Lijiadong** [comment]
这里有一个别人开源出来的转换结果：[https://huggingface.co/peterchou/ernie-gram](https://huggingface.co/peterchou/ernie-gram)

**Comment by nghuyong** [comment]
已经更新啦！！！欢迎体验！！
