### ISSUE TITLE
Conversion of ERNIE-M

### ISSUE THREAD

**Issue by piotrgramacki** [nghuyong/ERNIE-Pytorch#42]
Hi,
is it possible to convert the new [ERNIE-M](https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m) model to huggingface using this code? I had no luck with it, as it comes without `saved_weights.pdparams` params.

**Comment by piotrgramacki** [comment]
Thank you for your response and explanation.

**Comment by surajnair04** [comment]
@nghuyong I am interested in the ERNIE-M checkpoint that you converted to PyTorch. 
Is there a way you can share it with me?
