### ISSUE TITLE
ernie-1.0转换后的pytorch模型训练结果比paddlenlp好1个点以上。。。

### ISSUE THREAD

**Issue by EEeEhh** [nghuyong/ERNIE-Pytorch#43]
同一份中文文本分类数据集，训练参数保持相同。预训练权重是ernie-1.0。
pytorch用的是作者转换的权重，paddlenlp用的是其自带的。跑完之后指标相差1个点以上，有点奇怪？

**Comment by nghuyong** [comment]
这个问题可以去paddlenlp下面开一个issue问一下😂
