### ISSUE TITLE
更改词典

### ISSUE THREAD

**Issue by Joyxj** [nghuyong/ERNIE-Pytorch#45]
你好，ernie支持添加特殊符号到词表吗？

**Comment by nghuyong** [comment]
依托本项目，你可以把ernie转换成huggingface transformer的形式
如果在huggingface transformer添加新的token，参考：https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.add_tokens

**Comment by Joyxj** [comment]
> 依托本项目，你可以把ernie转换成huggingface transformer的形式 如果在huggingface transformer添加新的token，参考：https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.add_tokens

好的，谢谢
