### ISSUE TITLE
ernie模型下载

### ISSUE THREAD

**Issue by sunxiaojie99** [nghuyong/ERNIE-Pytorch#47]
请问ernie系列模型的下载链接在paddle哪个地方呢，https://github.com/PaddlePaddle/ERNIE/tree/ernie-kit-open-v1.0/applications/models_hub，我在这里发现下下来的模型里没有saved_weights～

**Comment by sunxiaojie99** [comment]
比如 2.0的zh版本，or 3.0的zh版本，十分感谢！🙏

**Comment by nghuyong** [comment]
目前已经迁移到了paddleNLP这个仓库下面了，例如 ernie-3.0: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0

**Comment by sunxiaojie99** [comment]
十分感谢，但是这里面好像没有中文的2.0版本

**Comment by nghuyong** [comment]
对，这是因为百度官方就没有开源2.0的中文版本
