### ISSUE TITLE
大佬，可以添加ernie-health吗

### ISSUE THREAD

**Issue by caoxu915683474** [nghuyong/ERNIE-Pytorch#48]

**Comment by nghuyong** [comment]
收到，会近期支持

**Comment by nghuyong** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-health
没看到预训练好的模型下载地址？ @caoxu915683474

**Comment by caoxu915683474** [comment]
https://github.com/PaddlePaddle/Research/tree/master/KG/eHealth

**Comment by nghuyong** [comment]
已经添加了哈，查看最新的readme
