### ISSUE TITLE
BertForMaskedLM预测错误的修复方法

### ISSUE THREAD

**Issue by Dopaminezsy** [nghuyong/ERNIE-Pytorch#50]
您好，尝试用huggingface里面的BertForMaskedLM去加载您转换的模型，然后预测被mask的词语，发现预测到的结果并不正确，请问这是什么原因？
您是否知道大概原因？我可以手动修复吗？

**Comment by Dopaminezsy** [comment]
@nghuyong 可能得原因是，ernie-2.0-en里面涉及task_type_vocab_size和对应的embedding吗？

**Comment by nghuyong** [comment]
可以的，非常感谢，欢迎提交mr

**Comment by Dopaminezsy** [comment]
> 可以的，非常感谢，欢迎提交mr

感谢回复。现在还有些疑惑，不太确定ernie2.0的mlm model，和huggingface里面的BertForMaskedLM区别在哪里？不知道您是否有相关经验？

**Comment by nghuyong** [comment]
我的经验是直接看模型的结构以及参数；需要对比两者的代码

**Comment by nghuyong** [comment]
@Dopaminezsy  ernie-2.0百度开源的模型为 BertModel 而非 BertForMaskedLM 所以没有最后mlm层的参数。所以ernie2.0的模型不能用于mlm的预测任务
