### ISSUE TITLE
您好！很高兴看到你的程序，但是我现在使用你的脚本convert_ernie3.0.py将 NENIE3.0转换 为Pytorch版本时，中间虽然没有出现任何问题，但是原先的模型大小为450M++，但是转换后怎么只有980k了呢？这个是中间漏掉了一些权重么？

### ISSUE THREAD

**Issue by Shajiu** [nghuyong/ERNIE-Pytorch#54]
您好！很高兴看到你的程序，但是我现在使用你的脚本convert_ernie3.0.py将 NENIE3.0转换 为Pytorch版本时，中间虽然没有出现任何问题，但是原先的模型大小为450M++，但是转换后怎么只有980k了呢？这个是中间漏掉了一些权重么？

**Comment by wangszoo** [comment]
如果日志显示都跳过的话，就是权重名不对

**Comment by nghuyong** [comment]
已经支持ernie3.0模型，请参考reame进行调用
如果想自己转换可以执行`python convert_ernie3.0.py`
