### ISSUE TITLE
能否提供tensorflow版本的ernie模型？

### ISSUE THREAD

**Issue by Junbin-Liu** [nghuyong/ERNIE-Pytorch#56]
例如 BertModel(pytorch) 和 TFBertModel(Tensorflow), 或者请问huggingface能否对ernie直接转换成tensorflow版本？

**Comment by Junbin-Liu** [comment]
目前看 huggingface 支持 Bert/GPT/GPT-2/Transformer-XL/XLNet/XLM？

**Comment by nghuyong** [comment]
目前不能，不过可以参考BERT的转换进行转换。

**Comment by Junbin-Liu** [comment]
你好，你的邮件我已经收到，我会尽快回复，谢谢
