### ISSUE TITLE
ernie-3.0-nano-zh的fill-mask版本

### ISSUE THREAD

**Issue by Smile-L-up** [nghuyong/ERNIE-Pytorch#58]
大佬您好，我发现开源的版本类型是feature extration。但是我想将ernie-3.0-nano-zh作为蒸馏的学生模型。feature extration类型好像不好继续微调，想请教一下您可以开源fill-mask类型的模型吗？或者根据您给的方法，我自己可以转换吗？

**Comment by nghuyong** [comment]
这是因为百度官方开源的就是“feature extration类型”的模型，没有开源最后MLM层的参数

**Comment by Smile-L-up** [comment]
感谢您的回复，我查看了一下paddle那个。好像有人直接加载继续微调，不知道本仓库的代码是否可以直接加载再微调。

**Comment by nghuyong** [comment]
可以，相当于MLM层随机初始化

**Comment by Smile-L-up** [comment]
好的，感谢回复。
