### ISSUE TITLE
convert脚本执行报错怎么办？

### ISSUE THREAD

**Issue by Faith-Uchiha** [nghuyong/ERNIE-Pytorch#60]
我用[这个仓库](https://github.com/PaddlePaddle/ERNIE)里的脚本下载了ernie-3.0-base的模型权重以及config文件，然后跑convert.py发现报错了，感觉是缺了一个key，但具体什么问题不太清楚，可以帮忙看看吗？

下载后的权重文件夹包括以下内容
![image](https://user-images.githubusercontent.com/26248309/197255419-c1ea338f-6f3b-45dd-a4e2-bb4251a4d32b.png)

执行脚本报错
![image](https://user-images.githubusercontent.com/26248309/197255462-096eb661-6c65-45e0-8374-e4b96de3a29e.png)

**Comment by Faith-Uchiha** [comment]
想要自己转换的原因是在huggingface那里下载ernie-3.0的模型之后用BertModel加载会有很多参数没加载上，而我用的transformers版本是4.18，因此没有ErnieModel这个类，所以想自己转换

**Comment by nghuyong** [comment]
https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/ERNIE/contents.html

**Comment by Faith-Uchiha** [comment]
没明白，我这出错具体是什么问题导致的呢？ 另外你给的链接里只给了模型名称也没有下载地址。

**Comment by nghuyong** [comment]
```
paddlenlp.transformers.ErnieTokenizer.from_pretrained("ernie-1.0-base-zh")
```
运行会自动帮你下载官方的paddle模型，这里的名字可以换成其他的模型
下载的文件存在 `~/.paddlenlp/models/`
