### ISSUE TITLE
您好，是否可以获取得到您所转换的ERNIE-M权重？

### ISSUE THREAD

**Issue by weikang-wang** [nghuyong/ERNIE-Pytorch#61]
我看到之前的issue提到获取得到的Ernie-m缺少pooler，和sent_embedding ,正好我不需要这两个，想问一下是否能获取得到您转换成hugging face形式后的模型和文件，感谢🙏

**Comment by nghuyong** [comment]
您好，有官方的ernie-m模型文件了吗

**Comment by weikang-wang** [comment]
嗯嗯，是的，已经开源了。在这里[
](https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m)

**Comment by weikang-wang** [comment]
嗯嗯，是的已经开源了。在这里

[https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-m](url)

**Comment by KnutJaegersberg** [comment]
I tinkered a bit, but I could not find the correct specification for the layers. Not very deep usually into Python, Ijust wanted Ernie-M to work. Would be nice to have Ernie-M seems the one of the best multilingual model and at least better than XLM-R.

**Comment by KnutJaegersberg** [comment]
They Paddlenlp added Ernie-M to huggingface repo, it can be used with paddlenlp.transformers. Still would be nice to have full support in huggingface ecosystem, which I'm more familiar with.

**Comment by KnutJaegersberg** [comment]
See also: 
https://github.com/huggingface/transformers/issues/21123

**Comment by nghuyong** [comment]
https://huggingface.co/docs/transformers/main/model_doc/ernie_m
已经实现了
