### ISSUE TITLE
请教关于 model_config.json 的疑问

### ISSUE THREAD

**Issue by RockNHawk** [nghuyong/ERNIE-Pytorch#69]
大佬您好，看到 test.py 中的这句代码。

`
 config = json.load(open(os.path.join(input_dir, 'model_config.json'), 'rt', encoding='utf-8'))
`

是从文心的模型中读取 `model_config.json`，不过我下载的文心原版模型中，并没有这文件，只有 
`ernie_config.json`，是不是哪里操作不对呢？

![image](https://github.com/nghuyong/ERNIE-Pytorch/assets/3222379/efc3b01b-85be-40e9-aadb-085b6778fd29)

![image](https://github.com/nghuyong/ERNIE-Pytorch/assets/3222379/3842a82b-5e32-42be-96c8-956a3a21c318)

**Comment by nghuyong** [comment]
test.py 并没有这句哦

**Comment by RockNHawk** [comment]
> test.py 并没有这句哦

抱歉说错，是 convert.py 中的

**Comment by nghuyong** [comment]
更新了readme，看这个部分，有模型下载的方式

`I want to convert the model from paddle version by myself 😉`
