### ISSUE TITLE
请问ernie3.0有没有能做生成任务的模型，

### ISSUE THREAD

**Issue by lzh1998-jansen** [nghuyong/ERNIE-Pytorch#71]
我想把文本分类，信息抽取等任务 全部转换成统一的生成任务。比如'这是哪个类型的文章：刘备白帝城托孤'。model生成  “历史”

**Comment by nghuyong** [comment]
可以的，参考https://huggingface.co/docs/transformers/model_doc/encoder-decoder

**Comment by lzh1998-jansen** [comment]
> 可以的，参考https://huggingface.co/docs/transformers/model_doc/encoder-decoder
感谢回复，我看了看这个链接，似乎这是在用seq-seq结构去做生成任务。我前段时间的构想是，用一个比较优秀的的中文小模型例如ernie，让他做decoder，配合prompt 的方式，来看看小模型有没有，做好生成任务的能力。
