### ISSUE TITLE
ERNIE 3.0是否可以商用？

### ISSUE THREAD

**Issue by FutureForMe** [nghuyong/ERNIE-Pytorch#73]
作者你好，我在百度的GitHub里面没有发现license（[https://github.com/PaddlePaddle/ERNIE](https://github.com/PaddlePaddle/ERNIE)），在您的仓库里面发现了ERNIE的license，想向您请教一下ERNIE 3.0是否可以商用呢？

**Comment by nghuyong** [comment]
可以，我这里只是转换的license，并且是MIT的license，是可以商用的
