### ISSUE TITLE
hi。由于huggingface更新了他们的版本，这里出现问题

### ISSUE THREAD

**Issue by ArrogantL** [nghuyong/ERNIE-Pytorch#8]
由于huggingface对代码进行了更新，现在模型文件需要重新命名才能使用。

```
  File "python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 430, in from_pretrained
    **kwargs
TypeError: 'NoneType' object is not iterable
```
问题在于huggingface将判定路径使用的配置文件名从 `bert_config.json` 更换为 `config.json` 。

将 `bert_config.json` 重命名为 `config.json` 即可解决该问题。

**Comment by nghuyong** [comment]
已经更新了代码，fix了bug
