### ISSUE TITLE
fluid_tensor转numpy出错

### ISSUE THREAD

**Issue by FrankWork** [nghuyong/ERNIE-Pytorch#9]
Traceback (most recent call last):
  File "./convert_ernie_to_pytorch.py", line 142, in <module>
    state_dict = extract_weights(args)
  File "./convert_ernie_to_pytorch.py", line 100, in extract_weights
    fluid_array = np.array(fluid_tensor, dtype=np.float32)
TypeError: __array__(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.Tensor) -> array

Invoked with: <paddle.fluid.core_avx.LoDTensor object at 0x7fb2ad4b4dc0>, dtype('float32')

**Comment by nghuyong** [comment]
已经更新了代码，fix了bug
